- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: false # DeltaV - Disable Senior Roles round start selection
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 14400 # Floofstation 4 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 2.0

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
