- type: job
  id: InventorySpecialist
  name: job-name-invspec
  description: job-description-invspec
  playTimeTracker: JobInventorySpecialist
  setPreference: true
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 57600 #16 hours
  antagAdvantage: 2 # DeltaV - Reduced TC: External Access
  startingGear: CargoTechGear
  icon: "JobIconInventorySpecialist"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Orders
  extendedAccess:
  - Salvage
  - Mail

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    id: InvSpecPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelCargoFilled
  duffelbag: ClothingBackpackDuffelCargoFilled
