- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  whitelisted: true
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics # DeltaV - Logistics Department replacing Cargo
      min: 28800 # Floofstation - 8 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 28800 # Floofstation - 8 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 28800 # Floofstation - 8 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 28800 # Floofstation - 8 hour
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Epistemics dept time requirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 28800 # Floofstation - 8 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 28800 # Floofstation - 8 hour
  weight: 20
  startingGear: CaptainGear
  icon: JobIconCaptain
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned # Goobstation - Nanotrasen owns your soul pal.
        soulOwnedNotDevil: true

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
