- type: department
  id: Miscellaneous
  description: department-Miscellaneous-description
  color: "#6e6e6e"
  weight: -10
  roles:
  #- Borg Got moved to Silicon department by StationAi
  - Passenger
  - Visitor
  - Prisoner # Nyanotrasen - Prisoner, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
  - Gladiator # Nyanotrasen - Gladiator, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
  - Anomaly
  - Freelancer
