- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Engineering
    min: 3600 # Floofstation - 1 hour
  antagAdvantage: 5 # Floof - Reduced TC: External Access + Fireaxe + Free Hardsuit, but they cannot pump chemicals into the air supply en masse.
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackAtmospherics
    shoes: ClothingShoesColorWhite
    id: AtmosPDA
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
