- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj  # Delta V - Change supervisor to chief justice
  access:
  - Service
  - Lawyer
  - Maintenance
  - Justice

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: HyperlinkBookSecuritySop # Floof - M3739 - Replacement of the standard BookSecurity that came originally. Throw the book at em!
    pocket2: RubberStampLawyer # Floof - M3739 - DeltaV's Lawyer stamp addition is now a pocket item instead to ensure deployment across loadouts. ClothingBackpackLawyerFilled and it's variants don't really work when people can choose their bags.
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
