- type: job
  id: Anomaly
  name: job-name-anomaly
  description: job-description-anomaly
  playTimeTracker: JobAnomaly
  startingGear: AnomalyGear
  alwaysUseSpawner: true
  overrideConsoleVisibility: true
  canBeAntag: false
  canBeAntagTarget: false
  icon: "JobIconNoId"
  joinNotifyCrew: false
  whitelisted: true
  access:
  - Maintenance
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Shadowkin
  special:
  - !type:AddComponentSpecial
    components:
      - type: AnomalyJob

- type: startingGear
  id: AnomalyGear
  equipment:
    jumpsuit: ClothingUniformNudityPermit
    shoes: ClothingClothWrap
    id: AnomalyIDCard
    ears: ClothingHeadsetGrey
