- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher #localized to mystic
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  setPreference: true #floof - this toggle allows players to ready up / create loadouts as senior roles. false disables it from the job list.
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 144000 # Floofstation 40 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.5 # So they can do brain surgery and cybernetic implants if there's no roboticist

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitSeniorResearcher
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
  innerClothingSkirt: ClothingUniformJumpskirtSeniorResearcher
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
