- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterTraitRequirement # Floofstation
    inverted: true
    traits:
      - Tiny # Floofstation - Too much of an advantage in a gunfight or stealth

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Medical dept time requirement
    department: Medical
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterTraitRequirement # Floofstation
    inverted: true
    traits:
      - Tiny # Floofstation - Too much of an advantage in a gunfight or stealth

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterTraitRequirement # Floofstation
    inverted: true
    traits:
      - Tiny # Floofstation - Too much of an advantage in a gunfight or stealth

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative
