- type: latheRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  category: Ammo
  completetime: 5
  materials:
    Steel: 50

- type: latheRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  category: Ammo
  completetime: 5
  materials:
     Steel: 210

- type: latheRecipe
  id: ClothingShoesBootsSecurityMagboots
  result: ClothingShoesBootsSecurityMagboots
  completetime: 10
  materials:
     Steel: 1000
     Plastic: 500

- type: latheRecipe
  id: SecSterileBag
  result: SterileBag
  completetime: 2
  materials:
    Plastic: 50
