- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
  - !type:CharacterDepartmentTimeRequirement #floof
      tracker: JobScientist #floof
      min: 9000 #2.5 hours floof
    - !type:CharacterOverallTimeRequirement
      min: 3600 # 1hr floof
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 3600 #floof
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 5
  canBeAntag: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      powerSlots: 2
  - !type:AddComponentSpecial
    components:
    - type: InnatePsionicPowers
      powersToAdd:
        - MetapsionicPower
        - TelepathyPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled
